reservedt = {
        
         'start':	1,
           'prog':	2,
           'body':	3,
       'declpart':	4,
       'decllist':	5,
      'decllist-':	6,
       'declstat':	7,
      'declstat-':	8,
           'type':	9,
       'procpart':	10,
       'proclist':	11,
           'proc':	12,
       'prochead':	13,
       'procname':	14,
      'null-list':	15,
      'fparmlist':	16,
     'fparmlist-':	17,
         'callby':	18,
       'execpart':	19,
       'exechead':	20,
       'statlist':	21,
      'statlist-':	22,
           'stat':	23,
         'instat':	24,
        'instat-':	25,
       'instathd':	26,
        'outstat':	27,
       'outstat-':	28,
      'outstathd':	29,
       'callstat':	30,
       'callname':	31,
      'aparmlist':	32,
     'aparmlist-':	33,
         'ifstat':	34,
         'ifthen':	35,
         'ifhead':	36,
        'forinit':	37,
          'forby':	38,
          'forto':	39,
        'forstat':	40,
     'assignstat':	41,
         'astat-':	42,
          'bexpr':	43,
         'orexpr':	44,
        'andexpr':	45,
       'andexpr-':	46,
        'notexpr':	47,
        'relexpr':	48,
          'aexpr':	49,
         'aexpr-':	50,
           'term':	51,
          'term-':	52,
        'primary':	53,
       'constant':	54,
            'END':	55,
        'PROGRAM':	56,
            'var':	57,
        'DECLARE':	58,
              ';':	59,
              ',':	60,
         'SCALAR':	61,
         'VECTOR':	62,
        'integer':	63,
         'MATRIX':	64,
             '::':	65,
        'INTEGER':	66,
           'REAL':	67,
      'PROCEDURE':	68,
              '{':	69,
              '}':	70,
          'VALUE':	71,
      'REFERENCE':	72,
        'EXECUTE':	73,
              '[':	74,
              ']':	75,
              ':':	76,
          'STDIN':	77,
         'string':	78,
          'STOUT':	79,
           'CALL':	80,
           'ELSE':	81,
             'IF':	82,
           'THEN':	83,
            'FOR':	84,
             '<-':	85,
             'BY':	86,
          'UNTIL':	87,
             'DO':	88,
              '|':	89,
              '&':	90,
              '!':	91,
              '<':	92,
             '<=':	93,
              '>':	94,
             '>=':	95,
             '==':	96,
             '!=':	97,
              '+':	98,
              '-':	99,
              '*':	100,
              '/':	101,
              '(':	102,
              ')':	103,
           'real':    	104,

}
asciidt ={ ';':23,
         ':':24,
         ',':25,
         '[':26,
         ']':27,
         '(':28,
         ')':29,
         '<':30,
         '>':31,
         '!':32,
         '+':33,
         '-':34,
         '*':35,
         '/':36,
         '{':37,
         '}':38,
         '&':39,
         '|':40,
         '==':41,
         '!=':42,
         '<=':43,
         '>=':44,
         '<-':45,
         '::':46}

relation_dict = { 'Equal to':1,
                  'Greater than':2,
                  'Less than':3
                }  
      

def get_value(reservedt,key):
    
    for k in reservedt:
      if reservedt[k] == key:
              return k

def get_list(reservedt,list_input):
    inp_str = " "
    for i in list_input:
         for k in reservedt:
               if reservedt[k] == int(i):
                   inp_str = inp_str +" " + k
    return inp_str               


              


